@server = http://localhost:4004
@service = /odata/v4/zform22
@namespace = com.sap.gateway.srvd.zsb_itemdetails.v0001
# local users from package.json [development]: P12345 (internal) / D11685 (dealer), empty password
@auth = Basic UDEyMzQ1Og==

### ------------------------------------------------------------------------
### 1. VALUE HELPS (Read-Only Entities)
### ------------------------------------------------------------------------

### Get all Dealers (ZI_OVS_VH)
GET {{server}}{{service}}/ZI_OVS_VH
Authorization: {{auth}}

### Get Invoices for a specific Dealer (ZI_OVS_INVOICE_VH)
GET {{server}}{{service}}/ZI_OVS_INVOICE_VH?$filter=kunnr eq '11685'
Authorization: {{auth}}

### Search for free Engines/Frames for Value Help (ZI_OVS_ENGINE_VH)
GET {{server}}{{service}}/ZI_OVS_ENGINE_VH?$filter=kunnr eq '11685' and invoice eq '117446714'&$top=10
Authorization: {{auth}}


### ------------------------------------------------------------------------
### 2. ITEM DETAILS (Main Table)
### ------------------------------------------------------------------------

### Get Item Details (Frames to Print) for a specific Invoice
GET {{server}}{{service}}/ZC_ITEMDETAILS?$filter=Kunnr eq '11685' and invoice eq '117446714'
Authorization: {{auth}}


### ------------------------------------------------------------------------
### 3. ACTIONS (call the real backend; use ids that exist there)
### ------------------------------------------------------------------------

### Check User Authorization (unbound action; the user comes from the login)
POST {{server}}{{service}}/checkUserAuth
Authorization: {{auth}}
Content-Type: application/json

{
  "lv_user": "",
  "is_authorized": false,
  "change_visi": false,
  "kunnr": "",
  "name1": ""
}

### Print Form 22 (Bound action to a specific row)
POST {{server}}{{service}}/ZC_ITEMDETAILS(Kunnr='11685',invoice='117446714',frameno='MBLJFN438SGG00008',engineno='JF17EYSGG00008')/{{namespace}}.printForm
Authorization: {{auth}}
Content-Type: application/json

{}

### Change Frame (Bound action to a specific row)
POST {{server}}{{service}}/ZC_ITEMDETAILS(Kunnr='11685',invoice='117446714',frameno='MBLJFN439SGG00009',engineno='JF17EYSGF00009')/{{namespace}}.changeFrame
Authorization: {{auth}}
Content-Type: application/json

{
  "matnr": "HDESHDRLMFINRD",
  "frameno_in": "MBLJFN43XSGG00032",
  "engineno_in": "JF17EYSGG00032"
}